const fs = require('fs');
let code = fs.readFileSync('src/app/layout.jsx', 'utf8');

// The meta tag is actually generated by Next.js's metadata object:
// appleWebApp: { capable: true ... }
// We can just add another meta in the <head> or change it if it's manual.
// Next.js automatically emits apple-mobile-web-app-capable when appleWebApp is set.
// It is deprecated, but Next.js 14 adds it automatically.
// We can suppress this by setting appleWebApp.capable = false or ignoring it,
// and manually adding <meta name="mobile-web-app-capable" content="yes" /> and <meta name="apple-mobile-web-app-capable" content="yes" /> if we want to manually control it, or just let Next.js do it and ignore the console warning.

// Let's add <meta name="mobile-web-app-capable" content="yes" /> in <head>
if (!code.includes('mobile-web-app-capable')) {
  code = code.replace(/<head>/, '<head>\n        <meta name="mobile-web-app-capable" content="yes" />');
  fs.writeFileSync('src/app/layout.jsx', code);
}
